### ISSUE TITLE
Preliminary user accounts

### ISSUE THREAD

**Issue by eteubert** [podlove/radiator-spark#9]
Some resources for authentication:

- [guardian](https://hex.pm/packages/guardian) (based on JWT https://jwt.io)
- [comeonin](https://hex.pm/packages/comeonin) (password hashing)
- I have a demo app for these https://github.com/eteubert/phoenix-auth-demo/ (maybe useful for a first look, however using outdated versions of Phoenix and the libraries above)

**Comment by eteubert** [comment]
Article discussing various authentication approaches (without dependencies): https://dockyard.com/blog/2017/08/01/authorization-for-phoenix-contexts

**Comment by monkeydom** [comment]
working on the user-accounts branch. The current state has the following additions:
* A user schema to have users in
* Guardian and JWT tokens to login
* The ability to send verification emails and generate corresponding tokens 
* Added the recent thoughts of eteubert as part of the documentation augemented a little bit by the status quo

Next up:
* Having a permissions model put onto the episode and podcast schemas to actually guard against users
* Adding some form of public visiblity too
* Add an interface to add users/sign up
* Ability to change password and/or email
